### PR TITLE
Update main-footer.production.config.json

### PR DESCRIPTION
**Pull request by fededrago**
Updated according to the latest version of the EOSC Portal content component main menu.

### CODE REVIEW

**Review by danielkryska — APPROVED** [review]

**Comment by fededrago** [comment]
Hi, may I ask why this update doesn't seem to be working?

**Comment by danielkryska** [comment]
Merged

**Comment by Marcelinna** [comment]
image

In footer we have double EOSC Projects, EOSC Association.

**Comment by danielkryska** [comment]
> Hi, may I ask why this update doesn't seem to be working?

Do you mean missing a comment with the URL providing to PR instance of lib?

**Comment by danielkryska** [comment]
In around 5 minutes changes will be available under URL https://s3.cloud.cyfronet.pl/eosc-portal-common/latest/index.production.html

**Comment by danielkryska** [comment]
Changes are available on production :)

**Comment by fededrago** [comment]
> Changes are available on production :)

Thank you Daniel!

**Pull request merged**
